### PR TITLE
Improve regexp for immature c-word

### PR DESCRIPTION
**Pull request by Alireza-Sampour**
Fix issue #6

### CODE REVIEW

**Comment by leo-galleguillos** [comment]
Couple more notes if you have a moment:

- Can you resolve the conflict?
- The unit test should be in the same order as the immature words (alphabetical order).

Thanks!

**Comment by Alireza-Sampour** [comment]
> Couple more notes if you have a moment:
> 
>     * Can you resolve the conflict?
> 
>     * The unit test should be in the same order as the immature words (alphabetical order).
> 
> 
> Thanks!

Sure, I will be sent another request

**Comment by Alireza-Sampour** [comment]
@leo-galleguillos Conflict resolved.

**Comment by Alireza-Sampour** [comment]
Hi @leo-galleguillos, can you merge or close this pull request?? i'm waiting for you.

**Comment by leo-galleguillos** [comment]
Looks great! Thank you again for helping out with this.

By the way, I removed a few extra spaces:

https://github.com/monthly-basis/content-moderation/commit/428b36c0a108e0efe377120a0b01f0c13c7e8dae

**Pull request merged**
